import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Layer 1')
    add_bone_collection('Layer 2')
    add_bone_collection('Layer 3')
    add_bone_collection('Layer 4')
    add_bone_collection('Layer 5')
    add_bone_collection('Layer 8')
    add_bone_collection('Layer 17')
    add_bone_collection('тело')
    add_bone_collection('нога_L')
    add_bone_collection('нога_R')
    add_bone_collection('рука_L')
    add_bone_collection('рука_R')
    add_bone_collection('лицо_L')
    add_bone_collection('лицо_R')
    add_bone_collection('сумка')
    add_bone_collection('шарф')
    add_bone_collection('Face', ui_row=1, color_set_id=5)
    add_bone_collection('Face (Primary)', ui_row=2, ui_title='(Primary)', color_set_id=2)
    add_bone_collection('Face (Secondary)', ui_row=2, ui_title='(Secondary)', color_set_id=3)
    add_bone_collection('Torso', ui_row=4, color_set_id=3)
    add_bone_collection('Torso (Tweak)', ui_row=5, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Fingers', ui_row=7, color_set_id=6)
    add_bone_collection('Fingers (Detail)', ui_row=8, ui_title='(Detail)', color_set_id=5)
    add_bone_collection('Arm.L (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Arm.L (FK)', ui_row=11, ui_title='(FK)', color_set_id=5)
    add_bone_collection('Arm.L (Tweak)', ui_row=12, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Arm.R (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Arm.R (FK)', ui_row=11, ui_title='(FK)', color_set_id=5)
    add_bone_collection('Arm.R (Tweak)', ui_row=12, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=14, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=15, ui_title='(FK)', color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=16, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=14, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=15, ui_title='(FK)', color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=16, ui_title='(Tweak)', color_set_id=4)
    add_bone_collection('Root', ui_row=19, color_set_id=1)

    bones = {}

    bone = arm.edit_bones.new('face')
    bone.head = 0.0000, 0.0000, 1.7813
    bone.tail = 0.0000, 0.0000, 1.8725
    bone.roll = 0.0000
    bone.use_connect = False
    bones['face'] = bone.name
    bone = arm.edit_bones.new('jaw')
    bone.head = 0.0000, -0.0023, 1.8157
    bone.tail = 0.0000, -0.0991, 1.7289
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['jaw'] = bone.name
    bone = arm.edit_bones.new('forehead.L.001')
    bone.head = 0.0732, -0.0654, 1.9918
    bone.tail = 0.0796, -0.0939, 1.9307
    bone.roll = -0.1546
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = 0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = 0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.L.001'] = bone.name
    bone = arm.edit_bones.new('forehead.L')
    bone.head = 0.0256, -0.0897, 1.9860
    bone.tail = 0.0259, -0.1150, 1.9136
    bone.roll = -0.0030
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = 0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = 0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.L'] = bone.name
    bone = arm.edit_bones.new('forehead.L.002')
    bone.head = 0.0949, -0.0549, 1.9723
    bone.tail = 0.0916, -0.0747, 1.9214
    bone.roll = 0.0830
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = 0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = 0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.L.002'] = bone.name
    bone = arm.edit_bones.new('nose_bridge')
    bone.head = 0.0000, -0.1357, 1.8146
    bone.tail = 0.0000, -0.1039, 1.8560
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['nose_bridge'] = bone.name
    bone = arm.edit_bones.new('cheek.T.L')
    bone.head = 0.1013, -0.0422, 1.8832
    bone.tail = 0.0848, -0.0914, 1.8354
    bone.roll = -2.1898
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['cheek.T.L'] = bone.name
    bone = arm.edit_bones.new('brow.T.L')
    bone.head = 0.1013, -0.0422, 1.8832
    bone.tail = 0.0916, -0.0747, 1.9214
    bone.roll = -2.0854
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_segments = 5
    bones['brow.T.L'] = bone.name
    bone = arm.edit_bones.new('brow.T.L.001')
    bone.head = 0.0916, -0.0747, 1.9214
    bone.tail = 0.0796, -0.0939, 1.9307
    bone.roll = 0.7225
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_segments = 4
    bone.bbone_easein = 0.0
    bones['brow.T.L.001'] = bone.name
    bone = arm.edit_bones.new('ear.L')
    bone.head = 0.1073, 0.0175, 1.8498
    bone.tail = 0.1328, 0.0572, 1.8498
    bone.roll = 1.5711
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['ear.L'] = bone.name
    bone = arm.edit_bones.new('cheek.B.L')
    bone.head = 0.0348, -0.1013, 1.7848
    bone.tail = 0.0831, -0.0748, 1.8014
    bone.roll = -0.6565
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['cheek.B.L'] = bone.name
    bone = arm.edit_bones.new('nose_glue.L')
    bone.head = 0.0163, -0.1227, 1.8186
    bone.tail = 0.0348, -0.1013, 1.7848
    bone.roll = 2.9797
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['nose_glue.L'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head = 0.0515, -0.0589, 1.8835
    bone.tail = 0.0516, -0.1084, 1.8835
    bone.roll = -2.9729
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('forehead.R.001')
    bone.head = -0.0732, -0.0654, 1.9918
    bone.tail = -0.0796, -0.0939, 1.9307
    bone.roll = 0.1546
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = -0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = -0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.R.001'] = bone.name
    bone = arm.edit_bones.new('forehead.R')
    bone.head = -0.0256, -0.0897, 1.9860
    bone.tail = -0.0259, -0.1150, 1.9136
    bone.roll = 0.0030
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = -0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = -0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.R'] = bone.name
    bone = arm.edit_bones.new('forehead.R.002')
    bone.head = -0.0949, -0.0549, 1.9723
    bone.tail = -0.0916, -0.0747, 1.9214
    bone.roll = -0.0830
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_curveinx = -0.07500000298023224
    bone.bbone_curveinz = 0.05000000074505806
    bone.bbone_curveoutx = -0.019999999552965164
    bone.bbone_curveoutz = 0.019999999552965164
    bones['forehead.R.002'] = bone.name
    bone = arm.edit_bones.new('cheek.T.R')
    bone.head = -0.1013, -0.0422, 1.8832
    bone.tail = -0.0848, -0.0914, 1.8354
    bone.roll = 2.1898
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['cheek.T.R'] = bone.name
    bone = arm.edit_bones.new('brow.T.R')
    bone.head = -0.1013, -0.0422, 1.8832
    bone.tail = -0.0916, -0.0747, 1.9214
    bone.roll = 2.0854
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_segments = 5
    bones['brow.T.R'] = bone.name
    bone = arm.edit_bones.new('brow.T.R.001')
    bone.head = -0.0916, -0.0747, 1.9214
    bone.tail = -0.0796, -0.0939, 1.9307
    bone.roll = -0.7225
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bone.bbone_segments = 4
    bone.bbone_easein = 0.0
    bones['brow.T.R.001'] = bone.name
    bone = arm.edit_bones.new('ear.R')
    bone.head = -0.1073, 0.0175, 1.8498
    bone.tail = -0.1328, 0.0572, 1.8498
    bone.roll = -1.5711
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['ear.R'] = bone.name
    bone = arm.edit_bones.new('cheek.B.R')
    bone.head = -0.0348, -0.1013, 1.7848
    bone.tail = -0.0831, -0.0748, 1.8014
    bone.roll = 0.6565
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['cheek.B.R'] = bone.name
    bone = arm.edit_bones.new('nose_glue.R')
    bone.head = -0.0163, -0.1227, 1.8186
    bone.tail = -0.0348, -0.1013, 1.7848
    bone.roll = -2.9797
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['nose_glue.R'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head = -0.0515, -0.0589, 1.8835
    bone.tail = -0.0516, -0.1084, 1.8835
    bone.roll = 2.9729
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['face']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('chin.L')
    bone.head = 0.0384, -0.0728, 1.7442
    bone.tail = 0.0348, -0.1013, 1.7848
    bone.roll = -0.1941
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['chin.L'] = bone.name
    bone = arm.edit_bones.new('lip.B.L')
    bone.head = 0.0000, -0.1262, 1.7796
    bone.tail = 0.0198, -0.1222, 1.7802
    bone.roll = 0.1579
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['lip.B.L'] = bone.name
    bone = arm.edit_bones.new('lip.T.L')
    bone.head = 0.0000, -0.1301, 1.7863
    bone.tail = 0.0196, -0.1255, 1.7872
    bone.roll = 0.1336
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['lip.T.L'] = bone.name
    bone = arm.edit_bones.new('chin.R')
    bone.head = -0.0384, -0.0728, 1.7442
    bone.tail = -0.0348, -0.1013, 1.7848
    bone.roll = 0.1941
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['chin.R'] = bone.name
    bone = arm.edit_bones.new('lip.B.R')
    bone.head = 0.0000, -0.1262, 1.7796
    bone.tail = -0.0198, -0.1222, 1.7802
    bone.roll = -0.1579
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['lip.B.R'] = bone.name
    bone = arm.edit_bones.new('lip.T.R')
    bone.head = 0.0000, -0.1301, 1.7863
    bone.tail = -0.0196, -0.1255, 1.7872
    bone.roll = -0.1336
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['lip.T.R'] = bone.name
    bone = arm.edit_bones.new('chelust.003.L')
    bone.head = 0.1001, 0.0078, 1.8128
    bone.tail = 0.0888, -0.0006, 1.7881
    bone.roll = -0.2998
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['chelust.003.L'] = bone.name
    bone = arm.edit_bones.new('chelust.003.R')
    bone.head = -0.1001, 0.0078, 1.8128
    bone.tail = -0.0888, -0.0006, 1.7881
    bone.roll = 0.2998
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['jaw']]
    bones['chelust.003.R'] = bone.name
    bone = arm.edit_bones.new('nose')
    bone.head = 0.0000, -0.1292, 1.8080
    bone.tail = 0.0000, -0.1495, 1.8265
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['nose_bridge']]
    bones['nose'] = bone.name
    bone = arm.edit_bones.new('cheek.T.L.001')
    bone.head = 0.0848, -0.0914, 1.8354
    bone.tail = 0.0205, -0.1054, 1.8468
    bone.roll = 0.5163
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['cheek.T.L']]
    bones['cheek.T.L.001'] = bone.name
    bone = arm.edit_bones.new('brow.T.L.002')
    bone.head = 0.0796, -0.0939, 1.9307
    bone.tail = 0.0259, -0.1150, 1.9136
    bone.roll = -0.8583
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['brow.T.L.001']]
    bone.bbone_segments = 7
    bones['brow.T.L.002'] = bone.name
    bone = arm.edit_bones.new('cheek.B.L.001')
    bone.head = 0.0831, -0.0748, 1.8014
    bone.tail = 0.1046, -0.0036, 1.8281
    bone.roll = -0.3744
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['cheek.B.L']]
    bones['cheek.B.L.001'] = bone.name
    bone = arm.edit_bones.new('lid.B.L')
    bone.head = 0.0245, -0.0874, 1.8659
    bone.tail = 0.0371, -0.0914, 1.8637
    bone.roll = 0.2594
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['lid.B.L'] = bone.name
    bone = arm.edit_bones.new('lid.T.L')
    bone.head = 0.0843, -0.0715, 1.8767
    bone.tail = 0.0785, -0.0834, 1.8882
    bone.roll = 0.1755
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['lid.T.L'] = bone.name
    bone = arm.edit_bones.new('cheek.T.R.001')
    bone.head = -0.0848, -0.0914, 1.8354
    bone.tail = -0.0205, -0.1054, 1.8468
    bone.roll = -0.5163
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['cheek.T.R']]
    bones['cheek.T.R.001'] = bone.name
    bone = arm.edit_bones.new('brow.T.R.002')
    bone.head = -0.0796, -0.0939, 1.9307
    bone.tail = -0.0259, -0.1150, 1.9136
    bone.roll = 0.8583
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['brow.T.R.001']]
    bone.bbone_segments = 7
    bones['brow.T.R.002'] = bone.name
    bone = arm.edit_bones.new('cheek.B.R.001')
    bone.head = -0.0831, -0.0748, 1.8014
    bone.tail = -0.1046, -0.0036, 1.8281
    bone.roll = 0.3744
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['cheek.B.R']]
    bones['cheek.B.R.001'] = bone.name
    bone = arm.edit_bones.new('lid.B.R')
    bone.head = -0.0245, -0.0874, 1.8659
    bone.tail = -0.0371, -0.0914, 1.8637
    bone.roll = -0.2594
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['lid.B.R'] = bone.name
    bone = arm.edit_bones.new('lid.T.R')
    bone.head = -0.0843, -0.0715, 1.8767
    bone.tail = -0.0785, -0.0834, 1.8882
    bone.roll = -0.1755
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['lid.T.R'] = bone.name
    bone = arm.edit_bones.new('lip.B.L.001')
    bone.head = 0.0198, -0.1222, 1.7802
    bone.tail = 0.0348, -0.1013, 1.7848
    bone.roll = 0.0601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lip.B.L']]
    bone.bbone_segments = 4
    bone.bbone_easeout = 0.0
    bones['lip.B.L.001'] = bone.name
    bone = arm.edit_bones.new('lip.T.L.001')
    bone.head = 0.0196, -0.1255, 1.7872
    bone.tail = 0.0348, -0.1013, 1.7848
    bone.roll = -0.0420
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lip.T.L']]
    bone.bbone_segments = 4
    bone.bbone_easeout = 0.0
    bones['lip.T.L.001'] = bone.name
    bone = arm.edit_bones.new('lip.B.R.001')
    bone.head = -0.0198, -0.1222, 1.7802
    bone.tail = -0.0348, -0.1013, 1.7848
    bone.roll = -0.0601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lip.B.R']]
    bone.bbone_segments = 4
    bone.bbone_easeout = 0.0
    bones['lip.B.R.001'] = bone.name
    bone = arm.edit_bones.new('lip.T.R.001')
    bone.head = -0.0196, -0.1255, 1.7872
    bone.tail = -0.0348, -0.1013, 1.7848
    bone.roll = 0.0420
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lip.T.R']]
    bone.bbone_segments = 4
    bone.bbone_easeout = 0.0
    bones['lip.T.R.001'] = bone.name
    bone = arm.edit_bones.new('chelust.002.L')
    bone.head = 0.0888, -0.0006, 1.7881
    bone.tail = 0.0000, -0.0991, 1.7289
    bone.roll = -0.1419
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['chelust.003.L']]
    bones['chelust.002.L'] = bone.name
    bone = arm.edit_bones.new('chelust.002.R')
    bone.head = -0.0888, -0.0006, 1.7881
    bone.tail = 0.0000, -0.0991, 1.7289
    bone.roll = 0.1419
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['chelust.003.R']]
    bones['chelust.002.R'] = bone.name
    bone = arm.edit_bones.new('lid.B.L.001')
    bone.head = 0.0371, -0.0914, 1.8637
    bone.tail = 0.0513, -0.0923, 1.8609
    bone.roll = 0.0826
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.L']]
    bones['lid.B.L.001'] = bone.name
    bone = arm.edit_bones.new('lid.T.L.001')
    bone.head = 0.0785, -0.0834, 1.8882
    bone.tail = 0.0652, -0.0941, 1.8952
    bone.roll = -0.9627
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.L']]
    bones['lid.T.L.001'] = bone.name
    bone = arm.edit_bones.new('lid.B.R.001')
    bone.head = -0.0371, -0.0914, 1.8637
    bone.tail = -0.0513, -0.0923, 1.8609
    bone.roll = -0.0826
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.R']]
    bones['lid.B.R.001'] = bone.name
    bone = arm.edit_bones.new('lid.T.R.001')
    bone.head = -0.0785, -0.0834, 1.8882
    bone.tail = -0.0652, -0.0941, 1.8952
    bone.roll = 0.9627
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.R']]
    bones['lid.T.R.001'] = bone.name
    bone = arm.edit_bones.new('lid.B.L.002')
    bone.head = 0.0513, -0.0923, 1.8609
    bone.tail = 0.0653, -0.0907, 1.8616
    bone.roll = 0.0077
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.L.001']]
    bones['lid.B.L.002'] = bone.name
    bone = arm.edit_bones.new('lid.T.L.002')
    bone.head = 0.0652, -0.0941, 1.8952
    bone.tail = 0.0501, -0.0965, 1.8934
    bone.roll = 0.7601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.L.001']]
    bones['lid.T.L.002'] = bone.name
    bone = arm.edit_bones.new('lid.B.R.002')
    bone.head = -0.0513, -0.0923, 1.8609
    bone.tail = -0.0653, -0.0907, 1.8616
    bone.roll = -0.0077
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.R.001']]
    bones['lid.B.R.002'] = bone.name
    bone = arm.edit_bones.new('lid.T.R.002')
    bone.head = -0.0652, -0.0941, 1.8952
    bone.tail = -0.0501, -0.0965, 1.8934
    bone.roll = -0.7601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.R.001']]
    bones['lid.T.R.002'] = bone.name
    bone = arm.edit_bones.new('lid.B.L.003')
    bone.head = 0.0653, -0.0907, 1.8616
    bone.tail = 0.0801, -0.0792, 1.8699
    bone.roll = 0.8919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.L.002']]
    bones['lid.B.L.003'] = bone.name
    bone = arm.edit_bones.new('lid.T.L.003')
    bone.head = 0.0501, -0.0965, 1.8934
    bone.tail = 0.0349, -0.0957, 1.8847
    bone.roll = 0.3005
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.L.002']]
    bones['lid.T.L.003'] = bone.name
    bone = arm.edit_bones.new('lid.B.R.003')
    bone.head = -0.0653, -0.0907, 1.8616
    bone.tail = -0.0801, -0.0792, 1.8699
    bone.roll = -0.8919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.R.002']]
    bones['lid.B.R.003'] = bone.name
    bone = arm.edit_bones.new('lid.T.R.003')
    bone.head = -0.0501, -0.0965, 1.8934
    bone.tail = -0.0349, -0.0957, 1.8847
    bone.roll = -0.3005
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.R.002']]
    bones['lid.T.R.003'] = bone.name
    bone = arm.edit_bones.new('lid.B.L.004')
    bone.head = 0.0801, -0.0792, 1.8699
    bone.tail = 0.0843, -0.0715, 1.8767
    bone.roll = 0.0708
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.L.003']]
    bones['lid.B.L.004'] = bone.name
    bone = arm.edit_bones.new('lid.T.L.004')
    bone.head = 0.0349, -0.0957, 1.8847
    bone.tail = 0.0245, -0.0874, 1.8659
    bone.roll = 0.1612
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.L.003']]
    bones['lid.T.L.004'] = bone.name
    bone = arm.edit_bones.new('lid.B.R.004')
    bone.head = -0.0801, -0.0792, 1.8699
    bone.tail = -0.0843, -0.0715, 1.8767
    bone.roll = -0.0708
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.B.R.003']]
    bones['lid.B.R.004'] = bone.name
    bone = arm.edit_bones.new('lid.T.R.004')
    bone.head = -0.0349, -0.0957, 1.8847
    bone.tail = -0.0245, -0.0874, 1.8659
    bone.roll = -0.1612
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['lid.T.R.003']]
    bones['lid.T.R.004'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['face']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Face', 'Face (Primary)', 'Face (Secondary)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'secondary', 'Face (Secondary)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'primary', 'Face (Primary)')
    pbone = obj.pose.bones[bones['jaw']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 4', 'тело')
    pbone = obj.pose.bones[bones['forehead.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['forehead.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['forehead.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['nose_bridge']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['cheek.T.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['ear.L']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 4', 'лицо_L')
    pbone = obj.pose.bones[bones['cheek.B.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['nose_glue.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['forehead.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['forehead.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['forehead.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['cheek.T.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['ear.R']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 4', 'лицо_R')
    pbone = obj.pose.bones[bones['cheek.B.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['nose_glue.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.B.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.T.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.B.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.T.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chelust.003.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chelust.003.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['nose']]
    pbone.rigify_type = 'basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 4', 'тело')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['cheek.T.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['cheek.B.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['cheek.T.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['brow.T.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['cheek.B.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.B.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.T.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.B.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lip.T.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chelust.002.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['chelust.002.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.L.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.L.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.R.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.R.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.L.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.L.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.B.R.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')
    pbone = obj.pose.bones[bones['lid.T.R.004']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Layer 17')

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
