import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(6):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Root"
    arm.rigify_colors[0].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[0].normal = Color((0.4353, 0.1843, 0.4157))
    arm.rigify_colors[0].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "IK"
    arm.rigify_colors[1].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[1].normal = Color((0.6039, 0.0000, 0.0000))
    arm.rigify_colors[1].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Special"
    arm.rigify_colors[2].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[2].normal = Color((0.9569, 0.7882, 0.0471))
    arm.rigify_colors[2].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Tweak"
    arm.rigify_colors[3].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[3].normal = Color((0.0392, 0.2118, 0.5804))
    arm.rigify_colors[3].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "FK"
    arm.rigify_colors[4].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[4].normal = Color((0.1176, 0.5686, 0.0353))
    arm.rigify_colors[4].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Extra"
    arm.rigify_colors[5].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[5].normal = Color((0.9686, 0.2510, 0.0941))
    arm.rigify_colors[5].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[5].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Face', ui_row=1, color_set_id=5)
    add_bone_collection('Face (Primary)', ui_row=2, color_set_id=2)
    add_bone_collection('Face (Secondary)', ui_row=2, color_set_id=3)
    add_bone_collection('Torso', ui_row=3, color_set_id=3)
    add_bone_collection('Torso (Tweak)', ui_row=4, color_set_id=4)
    add_bone_collection('Fingers', ui_row=5, color_set_id=6)
    add_bone_collection('Fingers (Detail)', ui_row=6, color_set_id=5)
    add_bone_collection('Arm.L (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.L (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.L (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Arm.R (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.R (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.R (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Root', ui_row=17, color_set_id=1)
    add_bone_collection('hair', ui_row=13)
    add_bone_collection('Skirt', ui_row=14)
    add_bone_collection('Prop', ui_row=16)
    add_bone_collection('Bag', ui_row=15)
    add_bone_collection('Beard', ui_row=13)
    add_bone_collection('Glasses', ui_row=14)
    add_bone_collection('Hat', ui_row=15)

    bones = {}

    bone = arm.edit_bones.new('char_root')
    bone.head = 0.0000, 0.0000, 0.0000
    bone.tail = 0.0000, 0.1728, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['char_root'] = bone.name
    bone = arm.edit_bones.new('MCH-lace.004')
    bone.head = 0.0587, -0.1395, 0.8741
    bone.tail = 0.0493, -0.1401, 0.8865
    bone.roll = -0.5956
    bone.use_connect = False
    bones['MCH-lace.004'] = bone.name
    bone = arm.edit_bones.new('MCH-lace.005')
    bone.head = 0.0463, 0.0634, 0.8926
    bone.tail = 0.0376, 0.0657, 0.9054
    bone.roll = -0.5887
    bone.use_connect = False
    bones['MCH-lace.005'] = bone.name
    bone = arm.edit_bones.new('spine')
    bone.head = 0.0000, -0.0239, 0.7410
    bone.tail = 0.0000, -0.0239, 0.8186
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['char_root']]
    bones['spine'] = bone.name
    bone = arm.edit_bones.new('lace.006')
    bone.head = 0.0587, -0.1395, 0.8741
    bone.tail = 0.0417, -0.1406, 0.8966
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.004']]
    bones['lace.006'] = bone.name
    bone = arm.edit_bones.new('lace.007')
    bone.head = 0.0463, 0.0634, 0.8926
    bone.tail = 0.0305, 0.0674, 0.9157
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.005']]
    bones['lace.007'] = bone.name
    bone = arm.edit_bones.new('spine.001')
    bone.head = 0.0000, -0.0239, 0.8186
    bone.tail = 0.0000, -0.0124, 0.9403
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine']]
    bones['spine.001'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head = 0.0821, -0.0239, 0.7410
    bone.tail = 0.1101, -0.0200, 0.3915
    bone.roll = -0.0868
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head = -0.0821, -0.0239, 0.7410
    bone.tail = -0.1101, -0.0200, 0.3915
    bone.roll = 0.0868
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('toolBone')
    bone.head = -0.6188, 0.0000, 0.8800
    bone.tail = -0.6188, 0.0000, 0.4619
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['toolBone'] = bone.name
    bone = arm.edit_bones.new('bag')
    bone.head = 0.1438, -0.0595, 0.7660
    bone.tail = 0.1797, -0.0595, 0.6456
    bone.roll = 2.8517
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['bag'] = bone.name
    bone = arm.edit_bones.new('Cloth.L')
    bone.head = 0.1134, -0.1287, 0.7145
    bone.tail = 0.1523, -0.1365, 0.4347
    bone.roll = -0.1383
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.L'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.001')
    bone.head = 0.1040, 0.0746, 0.7145
    bone.tail = 0.1101, 0.1012, 0.4203
    bone.roll = -0.0276
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.L.001'] = bone.name
    bone = arm.edit_bones.new('Cloth.R')
    bone.head = -0.1134, -0.1287, 0.7145
    bone.tail = -0.1523, -0.1365, 0.4347
    bone.roll = 0.1383
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.R'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.001')
    bone.head = -0.1040, 0.0746, 0.7145
    bone.tail = -0.1101, 0.1012, 0.4203
    bone.roll = 0.0276
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.R.001'] = bone.name
    bone = arm.edit_bones.new('spine.003')
    bone.head = 0.0000, -0.0124, 0.9403
    bone.tail = 0.0000, 0.0263, 1.1525
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.001']]
    bones['spine.003'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head = 0.1101, -0.0200, 0.3915
    bone.tail = 0.1338, 0.0180, 0.0940
    bone.roll = -0.0712
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head = -0.1101, -0.0200, 0.3915
    bone.tail = -0.1338, 0.0180, 0.0940
    bone.roll = 0.0712
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('MCH-lace.002')
    bone.head = 0.1407, -0.1339, 0.7652
    bone.tail = 0.1233, -0.1351, 0.7884
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag']]
    bones['MCH-lace.002'] = bone.name
    bone = arm.edit_bones.new('MCH-lace.003')
    bone.head = 0.1322, 0.0417, 0.7668
    bone.tail = 0.1160, 0.0458, 0.7906
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag']]
    bones['MCH-lace.003'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.002')
    bone.head = 0.1523, -0.1365, 0.4347
    bone.tail = 0.1992, -0.1459, 0.0978
    bone.roll = -0.1383
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.L']]
    bones['Cloth.L.002'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.003')
    bone.head = 0.1101, 0.1012, 0.4203
    bone.tail = 0.1165, 0.1295, 0.1062
    bone.roll = -0.0276
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.L.001']]
    bones['Cloth.L.003'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.002')
    bone.head = -0.1523, -0.1365, 0.4347
    bone.tail = -0.1992, -0.1459, 0.0978
    bone.roll = 0.1383
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.R']]
    bones['Cloth.R.002'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.003')
    bone.head = -0.1101, 0.1012, 0.4203
    bone.tail = -0.1165, 0.1295, 0.1062
    bone.roll = 0.0276
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.R.001']]
    bones['Cloth.R.003'] = bone.name
    bone = arm.edit_bones.new('neck.001')
    bone.head = 0.0000, 0.0263, 1.1525
    bone.tail = 0.0000, 0.0082, 1.2446
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['neck.001'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head = 0.0236, 0.0051, 1.1090
    bone.tail = 0.1174, 0.0193, 1.0750
    bone.roll = 1.9751
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head = -0.0236, 0.0051, 1.1090
    bone.tail = -0.1174, 0.0193, 1.0750
    bone.roll = -1.9751
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('MCH-lace')
    bone.head = -0.0233, -0.1450, 0.9829
    bone.tail = -0.0503, -0.1468, 1.0188
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['MCH-lace'] = bone.name
    bone = arm.edit_bones.new('MCH-lace.001')
    bone.head = -0.0397, 0.0852, 1.0184
    bone.tail = -0.0648, 0.0916, 1.0551
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['MCH-lace.001'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head = 0.1338, 0.0180, 0.0940
    bone.tail = 0.1338, -0.0558, 0.0393
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head = -0.1338, 0.0180, 0.0940
    bone.tail = -0.1338, -0.0558, 0.0393
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('lace')
    bone.head = 0.1407, -0.1339, 0.7652
    bone.tail = 0.1125, -0.1358, 0.8027
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.002']]
    bones['lace'] = bone.name
    bone = arm.edit_bones.new('MCH-STR-lace.004')
    bone.head = 0.1407, -0.1339, 0.7652
    bone.tail = -0.0233, -0.1450, 0.9829
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.002']]
    bones['MCH-STR-lace.004'] = bone.name
    bone = arm.edit_bones.new('lace.001')
    bone.head = 0.1322, 0.0417, 0.7668
    bone.tail = 0.1093, 0.0475, 0.8004
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.003']]
    bones['lace.001'] = bone.name
    bone = arm.edit_bones.new('MCH-STR-lace.005')
    bone.head = 0.1322, 0.0417, 0.7668
    bone.tail = -0.0397, 0.0852, 1.0184
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['MCH-lace.003']]
    bones['MCH-STR-lace.005'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head = 0.0000, 0.0082, 1.2446
    bone.tail = 0.0000, 0.0082, 1.4389
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['neck.001']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head = 0.1174, 0.0193, 1.0750
    bone.tail = 0.2366, 0.0268, 0.9305
    bone.roll = 2.3830
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head = -0.1174, 0.0193, 1.0750
    bone.tail = -0.2366, 0.0268, 0.9305
    bone.roll = -2.3830
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head = 0.1338, -0.0558, 0.0393
    bone.tail = 0.1338, -0.1023, 0.0393
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('heel.02.L')
    bone.head = 0.1076, 0.0558, 0.0000
    bone.tail = 0.1629, 0.0558, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['heel.02.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head = -0.1338, -0.0558, 0.0393
    bone.tail = -0.1338, -0.1023, 0.0393
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('heel.02.R')
    bone.head = -0.1076, 0.0558, 0.0000
    bone.tail = -0.1629, 0.0558, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['heel.02.R'] = bone.name
    bone = arm.edit_bones.new('lace.002')
    bone.head = 0.0587, -0.1395, 0.8741
    bone.tail = 0.0305, -0.1414, 0.9115
    bone.roll = -0.5956
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['lace']]
    bones['lace.002'] = bone.name
    bone = arm.edit_bones.new('lace.003')
    bone.head = 0.0463, 0.0634, 0.8926
    bone.tail = 0.0233, 0.0693, 0.9262
    bone.roll = -0.5887
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['lace.001']]
    bones['lace.003'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head = 0.0432, -0.0706, 1.3350
    bone.tail = 0.0432, -0.1022, 1.3350
    bone.roll = 0.0001
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head = -0.0432, -0.0706, 1.3350
    bone.tail = -0.0432, -0.1022, 1.3350
    bone.roll = -0.0001
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('bone.01.L')
    bone.head = 0.0794, 0.1057, 1.3620
    bone.tail = 0.0891, 0.1229, 1.2131
    bone.roll = 3.0769
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['bone.01.L'] = bone.name
    bone = arm.edit_bones.new('bone.01.R')
    bone.head = -0.0794, 0.1057, 1.3620
    bone.tail = -0.0891, 0.1229, 1.2131
    bone.roll = -3.0769
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['bone.01.R'] = bone.name
    bone = arm.edit_bones.new('glasses')
    bone.head = 0.0000, -0.1307, 1.3340
    bone.tail = 0.0000, -0.1689, 1.3340
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['glasses'] = bone.name
    bone = arm.edit_bones.new('hat')
    bone.head = 0.0000, 0.0027, 1.4207
    bone.tail = 0.0000, 0.0457, 1.5236
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['hat'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head = 0.2366, 0.0268, 0.9305
    bone.tail = 0.3463, 0.0026, 0.7959
    bone.roll = 2.3925
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head = -0.2366, 0.0268, 0.9305
    bone.tail = -0.3463, 0.0026, 0.7959
    bone.roll = -2.3925
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('tip.L')
    bone.head = 0.1338, -0.1202, 0.0000
    bone.tail = 0.1338, -0.1415, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.L']]
    bones['tip.L'] = bone.name
    bone = arm.edit_bones.new('tip.R')
    bone.head = -0.1338, -0.1202, 0.0000
    bone.tail = -0.1338, -0.1415, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.R']]
    bones['tip.R'] = bone.name
    bone = arm.edit_bones.new('eye_up.L')
    bone.head = 0.0432, -0.0706, 1.3350
    bone.tail = 0.0432, -0.1010, 1.3517
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['eye_up.L'] = bone.name
    bone = arm.edit_bones.new('eye_down.L')
    bone.head = 0.0432, -0.0706, 1.3350
    bone.tail = 0.0432, -0.0976, 1.3162
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['eye_down.L'] = bone.name
    bone = arm.edit_bones.new('eye_up.R')
    bone.head = -0.0432, -0.0706, 1.3350
    bone.tail = -0.0432, -0.1010, 1.3517
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['eye_up.R'] = bone.name
    bone = arm.edit_bones.new('eye_down.R')
    bone.head = -0.0432, -0.0706, 1.3350
    bone.tail = -0.0432, -0.0976, 1.3162
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['eye_down.R'] = bone.name
    bone = arm.edit_bones.new('bone.02.L')
    bone.head = 0.0891, 0.1229, 1.2131
    bone.tail = 0.0987, 0.1402, 1.0640
    bone.roll = -0.0647
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.01.L']]
    bones['bone.02.L'] = bone.name
    bone = arm.edit_bones.new('bone.02.R')
    bone.head = -0.0891, 0.1229, 1.2131
    bone.tail = -0.0987, 0.1402, 1.0640
    bone.roll = 0.0647
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.01.R']]
    bones['bone.02.R'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head = 0.3463, 0.0026, 0.7959
    bone.tail = 0.3763, -0.0034, 0.7529
    bone.roll = 2.5652
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head = -0.3463, 0.0026, 0.7959
    bone.tail = -0.3763, -0.0034, 0.7529
    bone.roll = -2.5652
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('bone.03.L')
    bone.head = 0.0987, 0.1402, 1.0640
    bone.tail = 0.1084, 0.1574, 0.9151
    bone.roll = -0.0647
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.02.L']]
    bones['bone.03.L'] = bone.name
    bone = arm.edit_bones.new('bone.03.R')
    bone.head = -0.0987, 0.1402, 1.0640
    bone.tail = -0.1084, 0.1574, 0.9151
    bone.roll = 0.0647
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['bone.02.R']]
    bones['bone.03.R'] = bone.name
    bone = arm.edit_bones.new('palm.01.L')
    bone.head = 0.3660, -0.0263, 0.7811
    bone.tail = 0.3993, -0.0410, 0.7408
    bone.roll = -2.1880
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.01.L'] = bone.name
    bone = arm.edit_bones.new('palm.02.L')
    bone.head = 0.3707, -0.0110, 0.7796
    bone.tail = 0.4041, -0.0208, 0.7408
    bone.roll = -2.2463
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.02.L'] = bone.name
    bone = arm.edit_bones.new('palm.03.L')
    bone.head = 0.3705, 0.0035, 0.7794
    bone.tail = 0.4008, 0.0017, 0.7415
    bone.roll = -2.2759
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.03.L'] = bone.name
    bone = arm.edit_bones.new('palm.04.L')
    bone.head = 0.3624, 0.0189, 0.7750
    bone.tail = 0.3905, 0.0216, 0.7416
    bone.roll = -2.3031
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['palm.04.L'] = bone.name
    bone = arm.edit_bones.new('palm.01.R')
    bone.head = -0.3660, -0.0263, 0.7811
    bone.tail = -0.3993, -0.0410, 0.7408
    bone.roll = 2.1880
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.01.R'] = bone.name
    bone = arm.edit_bones.new('palm.02.R')
    bone.head = -0.3707, -0.0110, 0.7796
    bone.tail = -0.4041, -0.0208, 0.7408
    bone.roll = 2.2463
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.02.R'] = bone.name
    bone = arm.edit_bones.new('palm.03.R')
    bone.head = -0.3705, 0.0035, 0.7794
    bone.tail = -0.4008, 0.0017, 0.7415
    bone.roll = 2.2759
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.03.R'] = bone.name
    bone = arm.edit_bones.new('palm.04.R')
    bone.head = -0.3624, 0.0189, 0.7750
    bone.tail = -0.3905, 0.0216, 0.7416
    bone.roll = 2.3031
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['palm.04.R'] = bone.name
    bone = arm.edit_bones.new('f_index.01.L')
    bone.head = 0.3993, -0.0410, 0.7408
    bone.tail = 0.4161, -0.0479, 0.7028
    bone.roll = -1.8314
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('thumb.01.L')
    bone.head = 0.3504, -0.0241, 0.7810
    bone.tail = 0.3519, -0.0529, 0.7521
    bone.roll = 0.3936
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.L']]
    bones['thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.L')
    bone.head = 0.4041, -0.0208, 0.7408
    bone.tail = 0.4207, -0.0260, 0.6973
    bone.roll = -1.8427
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.02.L']]
    bones['f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.L')
    bone.head = 0.4008, 0.0017, 0.7415
    bone.tail = 0.4177, -0.0012, 0.7019
    bone.roll = -2.0091
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.03.L']]
    bones['f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.L')
    bone.head = 0.3905, 0.0216, 0.7416
    bone.tail = 0.4064, 0.0211, 0.7128
    bone.roll = -2.2307
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.04.L']]
    bones['f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('f_index.01.R')
    bone.head = -0.3993, -0.0410, 0.7408
    bone.tail = -0.4161, -0.0479, 0.7028
    bone.roll = 1.8314
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('thumb.01.R')
    bone.head = -0.3504, -0.0241, 0.7810
    bone.tail = -0.3519, -0.0529, 0.7521
    bone.roll = -0.3936
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.01.R']]
    bones['thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.R')
    bone.head = -0.4041, -0.0208, 0.7408
    bone.tail = -0.4207, -0.0260, 0.6973
    bone.roll = 1.8427
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.02.R']]
    bones['f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.R')
    bone.head = -0.4008, 0.0017, 0.7415
    bone.tail = -0.4177, -0.0012, 0.7019
    bone.roll = 2.0091
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.03.R']]
    bones['f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.R')
    bone.head = -0.3905, 0.0216, 0.7416
    bone.tail = -0.4064, 0.0211, 0.7128
    bone.roll = 2.2307
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['palm.04.R']]
    bones['f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('f_index.02.L')
    bone.head = 0.4161, -0.0479, 0.7028
    bone.tail = 0.4219, -0.0510, 0.6794
    bone.roll = -1.6314
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.L']]
    bones['f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('thumb.02.L')
    bone.head = 0.3519, -0.0529, 0.7521
    bone.tail = 0.3605, -0.0691, 0.7240
    bone.roll = -0.0460
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.L']]
    bones['thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.L')
    bone.head = 0.4207, -0.0260, 0.6973
    bone.tail = 0.4273, -0.0278, 0.6700
    bone.roll = -1.7081
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.L']]
    bones['f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.L')
    bone.head = 0.4177, -0.0012, 0.7019
    bone.tail = 0.4235, -0.0026, 0.6786
    bone.roll = -1.8433
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.L']]
    bones['f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.L')
    bone.head = 0.4064, 0.0211, 0.7128
    bone.tail = 0.4138, 0.0210, 0.6947
    bone.roll = -2.1087
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.L']]
    bones['f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('f_index.02.R')
    bone.head = -0.4161, -0.0479, 0.7028
    bone.tail = -0.4219, -0.0510, 0.6794
    bone.roll = 1.6314
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.R']]
    bones['f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('thumb.02.R')
    bone.head = -0.3519, -0.0529, 0.7521
    bone.tail = -0.3605, -0.0691, 0.7240
    bone.roll = 0.0460
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.R']]
    bones['thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.R')
    bone.head = -0.4207, -0.0260, 0.6973
    bone.tail = -0.4273, -0.0278, 0.6700
    bone.roll = 1.7081
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.R']]
    bones['f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.R')
    bone.head = -0.4177, -0.0012, 0.7019
    bone.tail = -0.4235, -0.0026, 0.6786
    bone.roll = 1.8433
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.R']]
    bones['f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.R')
    bone.head = -0.4064, 0.0211, 0.7128
    bone.tail = -0.4138, 0.0210, 0.6947
    bone.roll = 2.1087
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.R']]
    bones['f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('f_index.03.L')
    bone.head = 0.4219, -0.0510, 0.6794
    bone.tail = 0.4253, -0.0529, 0.6601
    bone.roll = -1.5759
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.L']]
    bones['f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('thumb.03.L')
    bone.head = 0.3605, -0.0691, 0.7240
    bone.tail = 0.3697, -0.0768, 0.7018
    bone.roll = -0.1548
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.L']]
    bones['thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.L')
    bone.head = 0.4273, -0.0278, 0.6700
    bone.tail = 0.4302, -0.0290, 0.6493
    bone.roll = -1.6131
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.L']]
    bones['f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.L')
    bone.head = 0.4235, -0.0026, 0.6786
    bone.tail = 0.4272, -0.0037, 0.6597
    bone.roll = -1.7919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.L']]
    bones['f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.L')
    bone.head = 0.4138, 0.0210, 0.6947
    bone.tail = 0.4183, 0.0209, 0.6763
    bone.roll = -1.9706
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.L']]
    bones['f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('f_index.03.R')
    bone.head = -0.4219, -0.0510, 0.6794
    bone.tail = -0.4253, -0.0529, 0.6601
    bone.roll = 1.5759
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.R']]
    bones['f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('thumb.03.R')
    bone.head = -0.3605, -0.0691, 0.7240
    bone.tail = -0.3697, -0.0768, 0.7018
    bone.roll = 0.1548
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.R']]
    bones['thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.R')
    bone.head = -0.4273, -0.0278, 0.6700
    bone.tail = -0.4302, -0.0290, 0.6493
    bone.roll = 1.6131
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.R']]
    bones['f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.R')
    bone.head = -0.4235, -0.0026, 0.6786
    bone.tail = -0.4272, -0.0037, 0.6597
    bone.roll = 1.7919
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.R']]
    bones['f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.R')
    bone.head = -0.4138, 0.0210, 0.6947
    bone.tail = -0.4183, 0.0209, 0.6763
    bone.roll = 1.9706
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.R']]
    bones['f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['char_root']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Face', 'Face (Primary)', 'Face (Secondary)', 'Torso', 'Fingers', 'Arm.L (IK)', 'Arm.R (IK)', 'Leg.L (IK)', 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'diamond'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-lace.004']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (True, True, True)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('ARMATURE')
    con.name = 'Armature'
    tgt = con.targets.new()
    tgt.target = obj
    tgt.subtarget = 'MCH-STR-lace.004'
    tgt.weight = 1.000
    con.use_deform_preserve_volume = False
    con.use_bone_envelopes = False
    con.use_current_location = False
    con = pbone.constraints.new('COPY_SCALE')
    con.name = 'Copy Scale'
    con.target = None
    con.subtarget = 'char_root'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.power = 1.0
    con.use_make_uniform = False
    con.use_offset = False
    con.use_add = False
    pbone = obj.pose.bones[bones['MCH-lace.005']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('ARMATURE')
    con.name = 'Armature'
    tgt = con.targets.new()
    tgt.target = obj
    tgt.subtarget = 'MCH-STR-lace.005'
    tgt.weight = 1.000
    con.use_deform_preserve_volume = False
    con.use_bone_envelopes = False
    con.use_current_location = False
    con = pbone.constraints.new('COPY_SCALE')
    con.name = 'Copy Scale'
    con.target = None
    con.subtarget = 'char_root'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.power = 1.0
    con.use_make_uniform = False
    con.use_offset = False
    con.use_add = False
    pbone = obj.pose.bones[bones['spine']]
    pbone.rigify_type = 'game.spines.basic_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.pivot_pos = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['lace.006']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'sphere'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['lace.007']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.optional_widget_type = 'sphere'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.R (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.R (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toolBone']]
    pbone.rigify_type = 'game.basic.pivot'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    try:
        pbone.rigify_parameters.make_extra_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_parent_switch = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent_tags = 'injected'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bag']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L.001']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.R']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.R.001']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-lace.002']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-lace.003']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.L.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.R.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['neck.001']]
    pbone.rigify_type = 'game.spines.super_head'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.connect_chain = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-lace']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-lace.001']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (True, True, True)
    pbone.lock_rotation_w = True
    pbone.lock_scale = (True, True, True)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['lace']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_falloff_twist = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    con = pbone.constraints.new('DAMPED_TRACK')
    con.name = 'Damped Track'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'lace.006'
    con.track_axis = 'TRACK_Y'
    pbone = obj.pose.bones[bones['MCH-STR-lace.004']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_falloff_twist = True
    except AttributeError:
        pass
    con = pbone.constraints.new('STRETCH_TO')
    con.name = 'Stretch To'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-lace'
    con.volume = 'NO_VOLUME'
    con.keep_axis = 'SWING_Y'
    con.rest_length = 0.27282246947288513
    con.bulge = 1.0
    con.use_bulge_min = False
    con.use_bulge_max = False
    con.bulge_min = 1.0
    con.bulge_max = 1.0
    con.bulge_smooth = 0.0
    pbone = obj.pose.bones[bones['lace.001']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_use_scale = (False, False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_falloff_twist = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    con = pbone.constraints.new('DAMPED_TRACK')
    con.name = 'Damped Track'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'lace.007'
    con.track_axis = 'TRACK_Y'
    pbone = obj.pose.bones[bones['MCH-STR-lace.005']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_use_scale = (False, False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.skin_chain_falloff_twist = True
    except AttributeError:
        pass
    con = pbone.constraints.new('STRETCH_TO')
    con.name = 'Stretch To'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-lace.001'
    con.volume = 'NO_VOLUME'
    con.keep_axis = 'SWING_Y'
    con.rest_length = 0.30781587958335876
    con.bulge = 1.0
    con.use_bulge_min = False
    con.use_bulge_max = False
    con.bulge_min = 1.0
    con.bulge_max = 1.0
    con.bulge_smooth = 0.0
    pbone = obj.pose.bones[bones['head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.L (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.L (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.R (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.R (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['lace.002']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_LOCATION')
    con.name = 'Copy Location'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'lace.006'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.use_offset = False
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.subtarget = 'lace.006'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('COPY_SCALE')
    con.name = 'Copy Scale'
    con.target = obj
    con.subtarget = 'lace.006'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.power = 1.0
    con.use_make_uniform = False
    con.use_offset = False
    con.use_add = False
    pbone = obj.pose.bones[bones['lace.003']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_LOCATION')
    con.name = 'Copy Location'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'lace.007'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.use_offset = False
    con = pbone.constraints.new('COPY_ROTATION')
    con.name = 'Copy Rotation'
    con.target = obj
    con.subtarget = 'lace.007'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.euler_order = 'AUTO'
    con.mix_mode = 'REPLACE'
    con.use_offset = False
    con = pbone.constraints.new('COPY_SCALE')
    con.name = 'Copy Scale'
    con.target = obj
    con.subtarget = 'lace.007'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.power = 1.0
    con.use_make_uniform = False
    con.use_offset = False
    con.use_add = False
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.rigify_type = 'game.face.vizor_eye'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.angleMax = 5.0
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.rigify_type = 'game.face.vizor_eye'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.angleMax = 5.0
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.01.L']]
    pbone.rigify_type = 'game.basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.01.R']]
    pbone.rigify_type = 'game.basic.copy_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['glasses']]
    pbone.rigify_type = 'game.basic.prop'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Glasses')
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_parent_switch = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_controller = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deformer = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parents = 'ORG-hand.L, ORG-hand.R'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.default_parent = 'ORG-head'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hat']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Hat')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_up.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_down.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_up.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_down.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bone.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['bone.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'hair')
    pbone = obj.pose.bones[bones['palm.01.L']]
    pbone.rigify_type = 'game.limbs.super_palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.04.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.01.R']]
    pbone.rigify_type = 'game.limbs.super_palm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['palm.04.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YXZ'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
