import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color


def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(6):
        arm.rigify_colors.add()

    arm.rigify_colors[0].name = "Root"
    arm.rigify_colors[0].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[0].normal = Color((0.4353, 0.1843, 0.4157))
    arm.rigify_colors[0].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[0].standard_colors_lock = True
    arm.rigify_colors[1].name = "IK"
    arm.rigify_colors[1].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[1].normal = Color((0.6039, 0.0000, 0.0000))
    arm.rigify_colors[1].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[1].standard_colors_lock = True
    arm.rigify_colors[2].name = "Special"
    arm.rigify_colors[2].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[2].normal = Color((0.9569, 0.7882, 0.0471))
    arm.rigify_colors[2].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[2].standard_colors_lock = True
    arm.rigify_colors[3].name = "Tweak"
    arm.rigify_colors[3].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[3].normal = Color((0.0392, 0.2118, 0.5804))
    arm.rigify_colors[3].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[3].standard_colors_lock = True
    arm.rigify_colors[4].name = "FK"
    arm.rigify_colors[4].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[4].normal = Color((0.1176, 0.5686, 0.0353))
    arm.rigify_colors[4].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[4].standard_colors_lock = True
    arm.rigify_colors[5].name = "Extra"
    arm.rigify_colors[5].active = Color((0.5490, 1.0000, 1.0000))
    arm.rigify_colors[5].normal = Color((0.9686, 0.2510, 0.0941))
    arm.rigify_colors[5].select = Color((0.3137, 0.7843, 1.0000))
    arm.rigify_colors[5].standard_colors_lock = True

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Face', ui_row=1, color_set_id=5)
    add_bone_collection('Face (Primary)', ui_row=2, color_set_id=2)
    add_bone_collection('Face (Secondary)', ui_row=2, color_set_id=3)
    add_bone_collection('Torso', ui_row=3, color_set_id=3)
    add_bone_collection('Torso (Tweak)', ui_row=4, color_set_id=4)
    add_bone_collection('Fingers', ui_row=5, color_set_id=6)
    add_bone_collection('Fingers (Detail)', ui_row=6, color_set_id=5)
    add_bone_collection('Arm.L (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.L (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.L (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Arm.R (IK)', ui_row=7, color_set_id=2)
    add_bone_collection('Arm.R (FK)', ui_row=8, color_set_id=5)
    add_bone_collection('Arm.R (Tweak)', ui_row=9, color_set_id=4)
    add_bone_collection('Leg.L (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.L (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.L (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Leg.R (IK)', ui_row=10, color_set_id=2)
    add_bone_collection('Leg.R (FK)', ui_row=11, color_set_id=5)
    add_bone_collection('Leg.R (Tweak)', ui_row=12, color_set_id=4)
    add_bone_collection('Root', ui_row=17, color_set_id=1)
    add_bone_collection('hair', ui_row=13)
    add_bone_collection('Skirt', ui_row=14)
    add_bone_collection('Prop', ui_row=15)
    add_bone_collection('Bag', ui_row=15)
    add_bone_collection('Glasses', ui_row=14)
    add_bone_collection('Beard', ui_row=13)
    add_bone_collection('Hat', ui_row=16)

    bones = {}

    bone = arm.edit_bones.new('char_root')
    bone.head = 0.0000, 0.0000, 0.0000
    bone.tail = 0.0000, 0.1901, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bones['char_root'] = bone.name
    bone = arm.edit_bones.new('spine')
    bone.head = 0.0000, -0.0263, 0.6942
    bone.tail = 0.0000, -0.0263, 0.8076
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['char_root']]
    bones['spine'] = bone.name
    bone = arm.edit_bones.new('spine.001')
    bone.head = 0.0000, -0.0263, 0.8076
    bone.tail = 0.0000, -0.0253, 0.9827
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine']]
    bones['spine.001'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head = 0.1042, -0.0335, 0.7137
    bone.tail = 0.1155, -0.0213, 0.3935
    bone.roll = -0.0441
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head = -0.1042, -0.0335, 0.7137
    bone.tail = -0.1155, -0.0213, 0.3935
    bone.roll = 0.0441
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('toolBone')
    bone.head = -0.6188, 0.0000, 0.8800
    bone.tail = -0.6188, -0.0000, 0.4200
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['toolBone'] = bone.name
    bone = arm.edit_bones.new('CTRL_bag')
    bone.head = 0.2345, -0.0491, 0.7797
    bone.tail = 0.2771, -0.0491, 0.5287
    bone.roll = -0.1682
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['CTRL_bag'] = bone.name
    bone = arm.edit_bones.new('Cloth.L')
    bone.head = 0.1134, -0.1287, 0.7145
    bone.tail = 0.1523, -0.1365, 0.4347
    bone.roll = -0.1383
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.L'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.001')
    bone.head = 0.1040, 0.0746, 0.7145
    bone.tail = 0.1101, 0.1012, 0.4203
    bone.roll = -0.0276
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.L.001'] = bone.name
    bone = arm.edit_bones.new('Cloth.R')
    bone.head = -0.1134, -0.1287, 0.7145
    bone.tail = -0.1523, -0.1365, 0.4347
    bone.roll = 0.1383
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.R'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.001')
    bone.head = -0.1040, 0.0746, 0.7145
    bone.tail = -0.1101, 0.1012, 0.4203
    bone.roll = 0.0276
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine']]
    bones['Cloth.R.001'] = bone.name
    bone = arm.edit_bones.new('spine.003')
    bone.head = 0.0000, -0.0253, 0.9827
    bone.tail = -0.0000, 0.0038, 1.1627
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['spine.001']]
    bones['spine.003'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head = 0.1155, -0.0213, 0.3935
    bone.tail = 0.1262, 0.0196, 0.0957
    bone.roll = -0.0441
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head = -0.1155, -0.0213, 0.3935
    bone.tail = -0.1262, 0.0196, 0.0957
    bone.roll = 0.0441
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('MCH-bag.001')
    bone.head = 0.2342, -0.1861, 0.7832
    bone.tail = 0.2342, -0.1861, 0.7244
    bone.roll = 1.6151
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['CTRL_bag']]
    bones['MCH-bag.001'] = bone.name
    bone = arm.edit_bones.new('MCH-bag.002')
    bone.head = 0.2336, 0.0863, 0.7838
    bone.tail = 0.2336, 0.0863, 0.7250
    bone.roll = 1.5982
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['CTRL_bag']]
    bones['MCH-bag.002'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.002')
    bone.head = 0.1523, -0.1365, 0.4347
    bone.tail = 0.1992, -0.1459, 0.0978
    bone.roll = -0.1383
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.L']]
    bones['Cloth.L.002'] = bone.name
    bone = arm.edit_bones.new('Cloth.L.003')
    bone.head = 0.1101, 0.1012, 0.4203
    bone.tail = 0.1165, 0.1295, 0.1062
    bone.roll = -0.0276
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.L.001']]
    bones['Cloth.L.003'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.002')
    bone.head = -0.1523, -0.1365, 0.4347
    bone.tail = -0.1992, -0.1459, 0.0978
    bone.roll = 0.1383
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.R']]
    bones['Cloth.R.002'] = bone.name
    bone = arm.edit_bones.new('Cloth.R.003')
    bone.head = -0.1101, 0.1012, 0.4203
    bone.tail = -0.1165, 0.1295, 0.1062
    bone.roll = 0.0276
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Cloth.R.001']]
    bones['Cloth.R.003'] = bone.name
    bone = arm.edit_bones.new('neck.001')
    bone.head = -0.0000, 0.0038, 1.1627
    bone.tail = 0.0000, -0.0020, 1.2812
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['neck.001'] = bone.name
    bone = arm.edit_bones.new('shoulder.L')
    bone.head = 0.0776, 0.0111, 1.1576
    bone.tail = 0.1944, 0.0211, 1.1119
    bone.roll = 1.9016
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.L'] = bone.name
    bone = arm.edit_bones.new('shoulder.R')
    bone.head = -0.0776, 0.0111, 1.1576
    bone.tail = -0.1944, 0.0211, 1.1119
    bone.roll = -1.9016
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['spine.003']]
    bones['shoulder.R'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head = 0.1262, 0.0196, 0.0957
    bone.tail = 0.1295, -0.0505, 0.0390
    bone.roll = -0.1185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head = -0.1262, 0.0196, 0.0957
    bone.tail = -0.1295, -0.0505, 0.0390
    bone.roll = 0.1185
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('head')
    bone.head = 0.0000, -0.0020, 1.2812
    bone.tail = 0.0000, -0.0015, 1.5185
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['neck.001']]
    bones['head'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head = 0.1944, 0.0211, 1.1119
    bone.tail = 0.3276, 0.0304, 0.9448
    bone.roll = 2.3954
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('bag_top')
    bone.head = 0.1980, 0.0401, 1.2242
    bone.tail = 0.2002, 0.0400, 1.1807
    bone.roll = 1.5530
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.L']]
    bones['bag_top'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head = -0.1944, 0.0211, 1.1119
    bone.tail = -0.3276, 0.0304, 0.9448
    bone.roll = -2.3954
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['shoulder.R']]
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head = 0.1295, -0.0505, 0.0390
    bone.tail = 0.1342, -0.1285, 0.0391
    bone.roll = -0.0337
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('heel.02.L')
    bone.head = 0.0878, 0.0675, 0.0000
    bone.tail = 0.1964, 0.0675, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['heel.02.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head = -0.1295, -0.0505, 0.0390
    bone.tail = -0.1342, -0.1285, 0.0391
    bone.roll = 0.0337
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('heel.02.R')
    bone.head = -0.0878, 0.0675, 0.0000
    bone.tail = -0.1964, 0.0675, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['heel.02.R'] = bone.name
    bone = arm.edit_bones.new('eye.L')
    bone.head = 0.0464, -0.0804, 1.3793
    bone.tail = 0.0464, -0.1079, 1.3793
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.L'] = bone.name
    bone = arm.edit_bones.new('eye.R')
    bone.head = -0.0464, -0.0804, 1.3793
    bone.tail = -0.0464, -0.1079, 1.3793
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['eye.R'] = bone.name
    bone = arm.edit_bones.new('beard')
    bone.head = 0.0000, -0.1419, 1.1827
    bone.tail = 0.0000, -0.1717, 1.0788
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['beard'] = bone.name
    bone = arm.edit_bones.new('hat')
    bone.head = 0.0000, 0.0027, 1.4207
    bone.tail = 0.0000, 0.0457, 1.5236
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['hat'] = bone.name
    bone = arm.edit_bones.new('glasses')
    bone.head = 0.0000, -0.1362, 1.3754
    bone.tail = 0.0001, -0.1362, 1.3992
    bone.roll = 0.0036
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['head']]
    bones['glasses'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head = 0.3276, 0.0304, 0.9448
    bone.tail = 0.4481, 0.0059, 0.7971
    bone.roll = 2.4592
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('DEF-bag_front')
    bone.head = 0.2002, -0.0814, 1.1054
    bone.tail = 0.2342, -0.1861, 0.7832
    bone.roll = 1.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag_top']]
    bones['DEF-bag_front'] = bone.name
    bone = arm.edit_bones.new('DEF-bag_back')
    bone.head = 0.1808, 0.1335, 1.0836
    bone.tail = 0.2336, 0.0863, 0.7838
    bone.roll = 1.4071
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag_top']]
    bones['DEF-bag_back'] = bone.name
    bone = arm.edit_bones.new('MCH-bag_front')
    bone.head = 0.2002, -0.0814, 1.1054
    bone.tail = 0.2294, -0.0814, 1.1054
    bone.roll = 1.4928
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag_top']]
    bones['MCH-bag_front'] = bone.name
    bone = arm.edit_bones.new('MCH-bag_back')
    bone.head = 0.1808, 0.1335, 1.0836
    bone.tail = 0.2072, 0.1335, 1.0836
    bone.roll = 1.4071
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['bag_top']]
    bones['MCH-bag_back'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head = -0.3276, 0.0304, 0.9448
    bone.tail = -0.4481, 0.0059, 0.7971
    bone.roll = -2.4592
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('tip.L')
    bone.head = 0.1322, -0.1311, 0.0000
    bone.tail = 0.1322, -0.1545, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.L']]
    bones['tip.L'] = bone.name
    bone = arm.edit_bones.new('tip.R')
    bone.head = -0.1322, -0.1311, 0.0000
    bone.tail = -0.1322, -0.1545, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['toe.R']]
    bones['tip.R'] = bone.name
    bone = arm.edit_bones.new('eye_up.L')
    bone.head = 0.0464, -0.0804, 1.3793
    bone.tail = 0.0464, -0.1090, 1.3933
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['eye_up.L'] = bone.name
    bone = arm.edit_bones.new('eye_down.L')
    bone.head = 0.0464, -0.0804, 1.3793
    bone.tail = 0.0464, -0.1053, 1.3644
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.L']]
    bones['eye_down.L'] = bone.name
    bone = arm.edit_bones.new('eye_up.R')
    bone.head = -0.0464, -0.0804, 1.3793
    bone.tail = -0.0464, -0.1090, 1.3933
    bone.roll = 3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['eye_up.R'] = bone.name
    bone = arm.edit_bones.new('eye_down.R')
    bone.head = -0.0464, -0.0804, 1.3793
    bone.tail = -0.0464, -0.1053, 1.3644
    bone.roll = -3.1416
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['eye.R']]
    bones['eye_down.R'] = bone.name
    bone = arm.edit_bones.new('beard.001')
    bone.head = 0.0000, -0.1717, 1.0788
    bone.tail = 0.0000, -0.2015, 0.9748
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['beard']]
    bones['beard.001'] = bone.name
    bone = arm.edit_bones.new('hand.L')
    bone.head = 0.4481, 0.0059, 0.7971
    bone.tail = 0.5063, -0.0089, 0.7239
    bone.roll = 2.4958
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['hand.L'] = bone.name
    bone = arm.edit_bones.new('hand.R')
    bone.head = -0.4481, 0.0059, 0.7971
    bone.tail = -0.5063, -0.0089, 0.7239
    bone.roll = -2.4958
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['hand.R'] = bone.name
    bone = arm.edit_bones.new('f_index.01.L')
    bone.head = 0.4990, -0.0410, 0.7439
    bone.tail = 0.5159, -0.0466, 0.7051
    bone.roll = -1.9262
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_index.01.L'] = bone.name
    bone = arm.edit_bones.new('thumb.01.L')
    bone.head = 0.4495, -0.0213, 0.7783
    bone.tail = 0.4549, -0.0488, 0.7523
    bone.roll = 0.1385
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['thumb.01.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.L')
    bone.head = 0.5013, -0.0191, 0.7438
    bone.tail = 0.5191, -0.0239, 0.7012
    bone.roll = -1.8905
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_middle.01.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.L')
    bone.head = 0.4983, 0.0036, 0.7407
    bone.tail = 0.5158, 0.0000, 0.7028
    bone.roll = -2.0660
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_ring.01.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.L')
    bone.head = 0.4903, 0.0253, 0.7411
    bone.tail = 0.5056, 0.0239, 0.7147
    bone.roll = -2.2708
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.L']]
    bones['f_pinky.01.L'] = bone.name
    bone = arm.edit_bones.new('f_index.01.R')
    bone.head = -0.4990, -0.0410, 0.7439
    bone.tail = -0.5159, -0.0466, 0.7051
    bone.roll = 1.9262
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_index.01.R'] = bone.name
    bone = arm.edit_bones.new('thumb.01.R')
    bone.head = -0.4495, -0.0213, 0.7783
    bone.tail = -0.4549, -0.0488, 0.7523
    bone.roll = -0.1385
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['thumb.01.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.01.R')
    bone.head = -0.5013, -0.0191, 0.7438
    bone.tail = -0.5191, -0.0239, 0.7012
    bone.roll = 1.8905
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_middle.01.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.01.R')
    bone.head = -0.4983, 0.0036, 0.7407
    bone.tail = -0.5158, 0.0000, 0.7028
    bone.roll = 2.0660
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_ring.01.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.01.R')
    bone.head = -0.4903, 0.0253, 0.7411
    bone.tail = -0.5056, 0.0239, 0.7147
    bone.roll = 2.2708
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['hand.R']]
    bones['f_pinky.01.R'] = bone.name
    bone = arm.edit_bones.new('f_index.02.L')
    bone.head = 0.5159, -0.0466, 0.7051
    bone.tail = 0.5221, -0.0490, 0.6822
    bone.roll = -1.7614
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.L']]
    bones['f_index.02.L'] = bone.name
    bone = arm.edit_bones.new('thumb.02.L')
    bone.head = 0.4549, -0.0488, 0.7523
    bone.tail = 0.4632, -0.0659, 0.7241
    bone.roll = -0.0043
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.L']]
    bones['thumb.02.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.L')
    bone.head = 0.5191, -0.0239, 0.7012
    bone.tail = 0.5283, -0.0268, 0.6717
    bone.roll = -1.7847
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.L']]
    bones['f_middle.02.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.L')
    bone.head = 0.5158, 0.0000, 0.7028
    bone.tail = 0.5237, -0.0022, 0.6794
    bone.roll = -1.9459
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.L']]
    bones['f_ring.02.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.L')
    bone.head = 0.5056, 0.0239, 0.7147
    bone.tail = 0.5132, 0.0230, 0.6967
    bone.roll = -2.1387
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.L']]
    bones['f_pinky.02.L'] = bone.name
    bone = arm.edit_bones.new('f_index.02.R')
    bone.head = -0.5159, -0.0466, 0.7051
    bone.tail = -0.5221, -0.0490, 0.6822
    bone.roll = 1.7614
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.01.R']]
    bones['f_index.02.R'] = bone.name
    bone = arm.edit_bones.new('thumb.02.R')
    bone.head = -0.4549, -0.0488, 0.7523
    bone.tail = -0.4632, -0.0659, 0.7241
    bone.roll = 0.0043
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.01.R']]
    bones['thumb.02.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.02.R')
    bone.head = -0.5191, -0.0239, 0.7012
    bone.tail = -0.5283, -0.0268, 0.6717
    bone.roll = 1.7847
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.01.R']]
    bones['f_middle.02.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.02.R')
    bone.head = -0.5158, 0.0000, 0.7028
    bone.tail = -0.5237, -0.0022, 0.6794
    bone.roll = 1.9459
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.01.R']]
    bones['f_ring.02.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.02.R')
    bone.head = -0.5056, 0.0239, 0.7147
    bone.tail = -0.5132, 0.0230, 0.6967
    bone.roll = 2.1387
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.01.R']]
    bones['f_pinky.02.R'] = bone.name
    bone = arm.edit_bones.new('f_index.03.L')
    bone.head = 0.5221, -0.0490, 0.6822
    bone.tail = 0.5248, -0.0510, 0.6615
    bone.roll = -1.6158
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.L']]
    bones['f_index.03.L'] = bone.name
    bone = arm.edit_bones.new('thumb.03.L')
    bone.head = 0.4632, -0.0659, 0.7241
    bone.tail = 0.4718, -0.0739, 0.7014
    bone.roll = -0.1287
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.L']]
    bones['thumb.03.L'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.L')
    bone.head = 0.5283, -0.0268, 0.6717
    bone.tail = 0.5309, -0.0284, 0.6509
    bone.roll = -1.5877
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.L']]
    bones['f_middle.03.L'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.L')
    bone.head = 0.5237, -0.0022, 0.6794
    bone.tail = 0.5265, -0.0040, 0.6608
    bone.roll = -1.7601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.L']]
    bones['f_ring.03.L'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.L')
    bone.head = 0.5132, 0.0230, 0.6967
    bone.tail = 0.5179, 0.0220, 0.6783
    bone.roll = -1.9776
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.L']]
    bones['f_pinky.03.L'] = bone.name
    bone = arm.edit_bones.new('f_index.03.R')
    bone.head = -0.5221, -0.0490, 0.6822
    bone.tail = -0.5248, -0.0510, 0.6615
    bone.roll = 1.6158
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_index.02.R']]
    bones['f_index.03.R'] = bone.name
    bone = arm.edit_bones.new('thumb.03.R')
    bone.head = -0.4632, -0.0659, 0.7241
    bone.tail = -0.4718, -0.0739, 0.7014
    bone.roll = 0.1287
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thumb.02.R']]
    bones['thumb.03.R'] = bone.name
    bone = arm.edit_bones.new('f_middle.03.R')
    bone.head = -0.5283, -0.0268, 0.6717
    bone.tail = -0.5309, -0.0284, 0.6509
    bone.roll = 1.5877
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_middle.02.R']]
    bones['f_middle.03.R'] = bone.name
    bone = arm.edit_bones.new('f_ring.03.R')
    bone.head = -0.5237, -0.0022, 0.6794
    bone.tail = -0.5265, -0.0040, 0.6608
    bone.roll = 1.7601
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_ring.02.R']]
    bones['f_ring.03.R'] = bone.name
    bone = arm.edit_bones.new('f_pinky.03.R')
    bone.head = -0.5132, 0.0230, 0.6967
    bone.tail = -0.5179, 0.0220, 0.6783
    bone.roll = 1.9776
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['f_pinky.02.R']]
    bones['f_pinky.03.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['char_root']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Face', 'Face (Primary)', 'Face (Secondary)', 'Torso', 'Fingers', 'Arm.L (IK)', 'Arm.R (IK)', 'Leg.L (IK)', 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'diamond'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine']]
    pbone.rigify_type = 'game.spines.basic_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.pivot_pos = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.rotation_axis = 'x'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.rigify_type = 'game.limbs.leg'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.R (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.R (Tweak)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.rotation_axis = 'x'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toolBone']]
    pbone.rigify_type = 'game.basic.pivot'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Prop')
    try:
        pbone.rigify_parameters.make_extra_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_parent_switch = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.register_parent_tags = 'injected'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parents = 'torso, ORG-spine, ORG-spine.003, ORG-spine.006, ORG-shoulder.L, ORG-hand.L'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.default_parent = 'root'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.pivot_master_widget_type = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['CTRL_bag']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_tweaks = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L.001']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_ctrl = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_tweaks = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.R']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_ctrl = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_tweaks = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.R.001']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_ctrl = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_tweaks = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['spine.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-bag.001']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.optional_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-bag.002']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.optional_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Cloth.L.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.L.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.R.002']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['Cloth.R.003']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Skirt')
    pbone = obj.pose.bones[bones['neck.001']]
    pbone.rigify_type = 'game.spines.super_head'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.connect_chain = True
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.L']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['shoulder.R']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'shoulder'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.L (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.L (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.rotation_axis = 'x'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['bag_top']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.optional_widget_type = 'cube'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.rigify_type = 'game.limbs.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.R (Tweak)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.R (FK)')
    try:
        pbone.rigify_parameters.segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.enable_scale = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.rotation_axis = 'x'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['heel.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye.L']]
    pbone.rigify_type = 'game.face.vizor_eye'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye.R']]
    pbone.rigify_type = 'game.face.vizor_eye'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['beard']]
    pbone.rigify_type = 'game.basic.my_simple_tenticle'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Beard')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_chain_widget_type = 'circle'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.roll_alignment = 'manual'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.copy_rotation_axes = (False, False, False)
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.separate_rotation = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_tweaks = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.tweak_layers_extra = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.create_ctrl = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.fk_widget = 'bone'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hat']]
    pbone.rigify_type = 'game.basic.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Hat')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['glasses']]
    pbone.rigify_type = 'game.basic.pivot'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Glasses')
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_parent_switch = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_extra_deform = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parents = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.default_parent = 'ORG-head'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.add_extra_parents = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_parents = 'ORG-hand.R'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['DEF-bag_front']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_LOCATION')
    con.name = 'Copy Location'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-bag_front'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.use_offset = False
    con = pbone.constraints.new('STRETCH_TO')
    con.name = 'Stretch To'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-bag.001'
    con.volume = 'NO_VOLUME'
    con.keep_axis = 'SWING_Y'
    con.rest_length = 0.32962796092033386
    con.bulge = 1.0
    con.use_bulge_min = False
    con.use_bulge_max = False
    con.bulge_min = 1.0
    con.bulge_max = 1.0
    con.bulge_smooth = 0.0
    pbone = obj.pose.bones[bones['DEF-bag_back']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    con = pbone.constraints.new('COPY_LOCATION')
    con.name = 'Copy Location'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-bag_back'
    con.use_x = True
    con.use_y = True
    con.use_z = True
    con.invert_x = False
    con.invert_y = False
    con.invert_z = False
    con.use_offset = False
    con = pbone.constraints.new('STRETCH_TO')
    con.name = 'Stretch To'
    con.target = obj
    con.head_tail = 0.0
    con.use_bbone_shape = False
    con.subtarget = 'MCH-bag.002'
    con.volume = 'NO_VOLUME'
    con.keep_axis = 'SWING_Y'
    con.rest_length = 0.29832595586776733
    con.bulge = 1.0
    con.use_bulge_min = False
    con.use_bulge_max = False
    con.bulge_min = 1.0
    con.bulge_max = 1.0
    con.bulge_smooth = 0.0
    pbone = obj.pose.bones[bones['MCH-bag_front']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['MCH-bag_back']]
    pbone.rigify_type = 'game.basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Bag')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'bone'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['tip.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_up.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_down.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_up.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['eye_down.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_widget = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['beard.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Beard')
    pbone = obj.pose.bones[bones['hand.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['hand.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.L']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.01.R']]
    pbone.rigify_type = 'game.limbs.super_finger'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Fingers (Detail)')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_index.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thumb.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_middle.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_ring.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['f_pinky.03.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Fingers')
    try:
        pbone.rigify_parameters.enable_scale = True
    except AttributeError:
        pass

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
